#!/bin/bash

db_instance=$1
db_name=$2
db_pass=$3

function die() {
  echo "$@" >&2
  exit 1
}

if [[ "$#" != "3" ]]; then
  die "Usage: $0 [DB_INSTANCE] [DB_NAME] [DB_PASS]

This script prints to stdout the contents wp-config.php needs to work on php72.

DB_INSTANCE is the name of the MySQL instance to create.

DB_NAME is the name of the database to create within the MySQL instance.

DB_PASS is the root password to set for the instance.
"
fi

set -u
set -o pipefail

log=$(mktemp)

instances=$(mktemp)
gcloud sql instances describe $db_instance 2>$log >$instances \
  || die "Failed to get description of Cloud SQL instance $db_instance: $(cat $log)"
db_conn_name=$(grep connectionName $instances | sed 's/connectionName: //')
if [[ $? != 0 ]]; then die "Failed to find connectionName in instance description."; fi
db_host=":/cloudsql/$db_conn_name"
echo "\
<?php

// Temporary workaround for lack of \$_SERVER['HTTPS'] in php72.
\$_SERVER['HTTPS'] = \$_SERVER['HTTP_X_APPENGINE_HTTPS'];

// Use /tmp for uploads because /tmp is writable on the php72 runtime
// but the app directory tree is not. The wp-stateless plugin has to
// be enabled to make this work.
define('UPLOADS', '/tmp');

define( 'DB_NAME', '$db_name' );
define( 'DB_USER', 'root' );
define( 'DB_PASSWORD', '$db_pass' );
define( 'DB_HOST', '$db_host' );
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication Unique Keys and Salts from
 * {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 */" 2>$log \
	|| die "Failed to write top of wp-config.php: $(cat $log)"
curl https://api.wordpress.org/secret-key/1.1/salt/ 2>$log \
	|| die "Failed to curl unique keys and salts: $(cat $log)"
echo "
/**#@-*/

\$table_prefix = 'wp_';

define( 'WP_DEBUG', false );

/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', dirname( __FILE__ ) . '/' );
}

/** Sets up WordPress vars and included files. */
require_once( ABSPATH . 'wp-settings.php' );
" 2>$log || die "Failed to write bottom of wp-config.php: $(cat $log)"
