#!/bin/bash

function die() {
  echo "$@" >&2
  exit 1
}

set -u

log=$(mktemp)

echo "Fetching, unpacking and patching the latest version of WordPress."

curl -L https://wordpress.org/latest.tar.gz 2>$log >wordpress.tar.gz \
  || die "Failed to fetch latest version of WordPress: $(cat $log)"
tar xzvf wordpress.tar.gz &>$log || die "Failed to untar wordpress tarball: $(tail $log)"

curl -L https://github.com/wpCloud/wp-stateless/archive/2.1.1.tar.gz 2>$log >wp-stateless.tar.gz \
  || die "Failed to fetch wp-stateless plugin: $(cat $log)"
tar xzvf wp-stateless.tar.gz -C wordpress/wp-content/plugins &>$log \
  || die "Failed to untar wp-stateless tarball: $(tail $log)"
